services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "BikeBuilder!Dev2026"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000"
    ports:
      - "10000:10000"
    volumes:
      - azurite-data:/data

  servicebus-sql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "BikeBuilder!Bus2026"

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    depends_on:
      - servicebus-sql
    environment:
      ACCEPT_EULA: "Y"
      SQL_SERVER: servicebus-sql
      MSSQL_SA_PASSWORD: "BikeBuilder!Bus2026"
    ports:
      - "5672:5672"
      - "5300:5300"
    volumes:
      - ./servicebus-emulator/Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json

volumes:
  sql-data:
  azurite-data:
