services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "BikeBuilder!Dev2026"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000"
    ports:
      - "10000:10000"
    volumes:
      - azurite-data:/data

volumes:
  sql-data:
  azurite-data:
